### ISSUE TITLE
Where exactly do I put the images?

### ISSUE THREAD

**Issue by theSage21** [tanmay2893/Image-Sorting#1]
This is awesome! I have a different use in mind though. I'm not able to figure out where exactly are the images to be put? In the PWD?

**Comment by tanmay2893** [comment]
Place all the photographs in the same folder (wherever the code is) and run "face_train.py". Let me know if it works for you.

**Comment by theSage21** [comment]
I went through the code. This does not have what I was looking for. Nice script though. It feels very familiar to <http://hanzratech.in/2015/02/03/face-recognition-using-opencv.html>
